### ISSUE TITLE
How to kick off workflow

### ISSUE THREAD

**Issue by cgood92** [ReedD/dadoune.com#1]
@ReedD I really like your automated workflow with AWS.

I have read this article many times now: https://www.dadoune.com/blog/aws-codepipeline-cloudbuild-static-s3-website/.  But, what I don't see in that article is how you are kicking off everything.

When/where/how is `buildspec.yml` getting "invoked", or whatever the terminology is?

I'm also confused on where the `cfn-stack.json` talks to `buildspec.yml`.  I don't see either file pointing at the other, or invoking each other in anyway.

I think you have the solution to my problem, I'm just not sure what I'm missing.

**Comment by ReedD** [comment]
Hey @cgood92 AWS CodeBuild looks for `buildspec.yml` in your repo, you can read more about it [here](http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html). The whole process is kicked off by AWS CodePipeline every time you commit your code to GitHub. Does that answer your questions?
